#Created by webjeda - http://webjeda.com

# Site settings
encoding: utf-8
title: Respeto
author: Respeto
email: respetoriocuarto@gmail.com

# Server
baseurl: ""
url: "https://respeto.org.ar"

# Pagination configuration
paginate: 12
paginate_path: "noticias/page/:num"

# Tracker
analytics: UA-83979019-1

# Build settings
markdown: kramdown
permalink: pretty
sass:
 style: compressed
exclude:
- README.md
- LICENCE.md
- .gitignore

# Plugins
gems: [jekyll-paginate]

# Social Media settings
facebook_username: RespetoRioCuarto
twitter_username: SomosRespeto
youtube_username: UC4kjCFYZMhw7FLd_tcl21Gg
telefono_nro: (0358)  4671223
# direccion:
